name: bird-geospatial-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  # Core scientific python
  - numpy
  - pandas

  # Geospatial libraries
  # Coordinates and CRSs
  - pyproj>=3.0 # pyproj>=3.0 is required for proj>=8.0
  # Vector data
  - geopandas
  - geojson
  - pyogrio
  # Raster data
  - xarray
  - rioxarray

  # Interactive computing
  - ipython
  - ipykernal
  - nbconvert

  # Plotting
  # Matplotlib
  - Matplotlib
  - seaborn
  # Holoviews
  # --- Avoid compatibility issues with boken and new holoviews
  - holoviews<=1.19
  - hvplot
  - geoviews>=1.10

  # BirdNET
  - pip:
    - birdnet